---
title: "DATA 643 Prep: Chapter 5, Building Your Own Recommendation Engine"
output:
  html_document:
    theme: lumen

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Text

Building a Recommendation System with R
by Suresh K. Gorakala (Author), Michele Usuelli (Author) 
https://www.amazon.com/dp/B012O8S1YM/ref=dp-kindle-redirect?_encoding=UTF8&btkr=1

# Env Prep

```{r, message=F, warning=F}
library("data.table")
library("ggplot2")
library("recommenderlab")
library("countrycode")
```

# Data Preparation {.tabset .tabset-pills} 

## Importing the data

```{r}
file_in <- "anonymous-msweb.test.txt"
table_in <- read.csv(file_in, header=F)
head(table_in)
table_users <- table_in[, 1:2]
table_users <- data.table(table_users)
setnames(table_users, 1:2, c("category", "value"))
table_users <- table_users[category %in% c("C", "V")]
head(table_users)
```

## Defining a rating matrix

```{r}
table_users[, chunk_user := cumsum(category =="C")]
head(table_users)
table_long <- table_users[, list(user = value[1], item = value[-1]), by = "chunk_user"]
head(table_long)
table_long[, value := 1]
table_wide <- reshape(data = table_long,
                      direction = "wide", 
                      idvar = "user", 
                      timevar = "item", 
                      v.names = "value")
head(table_wide[, 1:5, with=F])
vector_users <- table_wide[, user]
table_wide <- table_wide[, user := NULL]
table_wide <- table_wide[, chunk_user := NULL]

setnames(x = table_wide,
         old=names(table_wide),
         new=substring(names(table_wide), 7))
matrix_wide <- as.matrix(table_wide)
rownames(matrix_wide) <- vector_users

## coerce to binary
matrix_wide[is.na(matrix_wide)] <- 0
ratings_matrix <- as(matrix_wide, "binaryRatingMatrix")
ratings_matrix
```

## Heatmap

```{r}
image(ratings_matrix[1:50, 1:50], main="Binary Rating Matrix")
```

## Distrubtion of Users

```{r}
n_users <- colCounts(ratings_matrix)
qplot(n_users[n_users > 100]) + stat_bin(bindwidth = 10) + ggtitle("Distribution of the number of users")
```

## Remove Items 

```{r}
# too few purchases
ratings_matrix <- ratings_matrix[, colCounts(ratings_matrix) >= 5]
ratings_matrix <- ratings_matrix[rowCounts(ratings_matrix) >= 5, ]
ratings_matrix
```

# Exacting Item Attributes

```{r}
table_in <- data.table(table_in)
table_items <- table_in[V1 == "A"]
head(table_items)
table_items <- table_items[, c(2, 4, 5), with = F]
setnames(table_items, 1:3, c("id", "description", "url"))
table_items <- table_items[order(id)]
head(table_items)
table_items <- table_items[, category := "product"]

name_countries <- c(countrycode_data$country.name.en, "Taiwan", "UK", "Russia",
                    "Venezuela", "Slovenija", "Caribbean", "Netherlands (Holland)",
                    "Europe", "Central America", "MS North Africa")
table_items <- table_items[description %in% name_countries, category := "region"]
table_items <- table_items[grepl("Region", description), category := "region"]
head(table_items)
table_items[, list(n_items= .N), by=category]
```

# Building the Model

```{r}


```